# /// script
# requires-python = ">=3.10"
# dependencies = ["numpy", "pandas", "pyarrow", "scipy"]
# ///
"""Fits the grind estimator's hyperparameters and default lead time to the
grinds in logs/ and writes them to grindy-gp/src/fitted.rs.

Run from the repo root: uv run tools/gp/fit.py
"""

import math

import numpy as np
from scipy.optimize import minimize

from common import MAX_LEAD_TIME, ROOT, Params, feed, load_grinds

# All logs share one grind setting, so they can't tell how much the mean flow
# rate varies between setups: fitting it drives it to 0, which would freeze
# the rate at the prior. A prior sd of 0.1 g/s keeps it learned per grind.
MEAN_RATE_PRIOR_VAR = 0.1**2


def params(theta) -> Params:
    return Params(
        length_scale=math.exp(theta[0]),
        rate_var=math.exp(theta[1]),
        noise_var=math.exp(theta[2]),
        mean_rate_prior=theta[3],
        mean_rate_prior_var=MEAN_RATE_PRIOR_VAR,
    )


def main() -> None:
    grinds = load_grinds()
    print(f"{len(grinds)} grinds")

    def nll(theta) -> float:
        return sum(feed(g, params(theta))[1] for g in grinds)

    result = minimize(
        nll,
        [math.log(0.02), math.log(1.0), math.log(0.025**2), 0.75],
        method="Nelder-Mead",
        options={"maxiter": 2000, "xatol": 1e-4, "fatol": 1e-3},
    )
    if not result.success:
        print(f"warning: optimizer did not converge: {result.message}")
    p = params(result.x)
    print(f"{p}\nnegative log likelihood {result.fun:.2f}")

    lead_times = []
    for g in grinds:
        if g.settled is None:
            print(f"{g.name}: no settled weight")
            continue
        est, _ = feed(g, p)
        lead_time = est.mean_crossing(g.settled)
        print(f"{g.name}: settled {g.settled:.2f} g, lead time {lead_time}")
        if lead_time is not None and 0.0 <= lead_time <= MAX_LEAD_TIME:
            lead_times.append(lead_time)
    default_lead_time = float(np.mean(lead_times))
    print(f"default lead time {default_lead_time:.3f} s from {len(lead_times)} grinds")

    (ROOT / "grindy-gp" / "src" / "fitted.rs").write_text(
        f"""//! Generated by `uv run tools/gp/fit.py` from the grinds in `logs/`.
//! Do not edit by hand, rerun the script instead.

use crate::Params;

/// GP hyperparameters maximizing the marginal likelihood of the logged
/// grinds (`mean_rate_prior_var` is fixed, see the script).
pub const FITTED: Params = Params {{
    length_scale: {p.length_scale:.6e},
    rate_var: {p.rate_var:.6e},
    noise_var: {p.noise_var:.6e},
    mean_rate_prior: {p.mean_rate_prior:.6e},
    mean_rate_prior_var: {p.mean_rate_prior_var:.6e},
}};

/// Mean lead time observed on the logged grinds, used until grindy has
/// learned its own.
pub const DEFAULT_LEAD_TIME: f32 = {default_lead_time:.6e};
"""
    )


if __name__ == "__main__":
    main()
