//! Generated by `uv run tools/gp/fit.py` from the grinds in `logs/`.
//! Do not edit by hand, rerun the script instead.

use crate::Params;

/// GP hyperparameters maximizing the marginal likelihood of the logged
/// grinds (`mean_rate_prior_var` is fixed, see the script).
pub const FITTED: Params = Params {
    length_scale: 1.575927e-02,
    rate_var: 1.000150e+00,
    noise_var: 1.216709e-03,
    mean_rate_prior: 7.629557e-01,
    mean_rate_prior_var: 1.000000e-02,
};

/// Mean lead time observed on the logged grinds, used until grindy has
/// learned its own.
pub const DEFAULT_LEAD_TIME: f32 = 4.858613e-01;
